compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.9.1.cjs

nodeLinker: pnp

pnpEnableEsmLoader: true

pnpMode: strict

packageExtensions:
  express-nunjucks@*:
    dependencies:
      express: "*"
  stylelint-config-standard@*:
    dependencies:
      stylelint: "*"
  typescript@*:
    dependencies:
      "@types/node": "*"
      "@types/jest": "*"
  jest@*:
    dependencies:
      "@types/jest": "*"
      "ts-jest": "*"
  ts-jest@*:
    dependencies:
      "@types/jest": "*"
  "@types/jest@*":
    dependencies:
      "@types/node": "*"
  "@hmcts/nodejs-logging@*":
    dependencies:
      "@types/node": "*"
  "govuk-frontend@*":
    dependencies:
      "@types/node": "*"
