compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  hmcts-cft:
    npmRegistryServer: "https://pkgs.dev.azure.com/hmcts/Artifacts/_packaging/hmcts-lib/npm/registry/"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
