compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmPreapprovedPackages:
  - '@hmcts-cft/docweave@0.2.0'
  - 'prosemirror-dropcursor@1.8.4'

yarnPath: .yarn/releases/yarn-4.18.0.cjs

npmScopes:
  hmcts-cft:
    npmRegistryServer: 'https://pkgs.dev.azure.com/hmcts/Artifacts/_packaging/hmcts-lib/npm/registry/'
