export default {
  'start-now': 'startNow',
  'free-legal-advice': 'freeLegalAdvice',
  home: 'home',
  'page-not-found': 'pageNotFound',
  'defendant-name-capture': 'defendantNameCapture',
  'defendant-name-confirmation': 'defendantNameConfirmation',
  'contact-preferences-telephone': 'contactPreferencesTelephone',
  'contact-preferences-text-message': 'contactPreferencesTextMessage',
  'dispute-claim-interstitial': 'disputeClaimInterstitial',
  'date-of-birth': 'dateOfBirth',
  'confirmation-of-notice-date-when-not-provided': 'noticeDateWhenNotProvided',
  'confirmation-of-notice-given': 'confirmationOfNoticeGiven',
  'non-rent-arrears-dispute': 'nonRentArrearsDispute',
  'confirmation-of-notice-date-when-provided': 'noticeDateWhenProvided',
  'rent-arrears-dispute': 'rentArrearsDispute',
  'payment-interstitial': 'paymentInterstitial',
  'repayments-made': 'repaymentsMade',
  'landlord-registered': 'landlordRegistered',
  'tenancy-date-unknown': 'tenancyDateUnknown',
  'tenancy-date-details': 'tenancyDateDetails',
  'landlord-licensed': 'landlordLicensed',
  'written-terms': 'writtenTerms',
  'contact-preferences-email-or-post': 'contactPreferenceEmailOrPost',
  'instalment-payments': 'instalmentPayments',
  'how-Much-Afford-To-Pay': 'howMuchAffordToPay',
};
