export default {
  'start-now': 'startNow',
  'free-legal-advice': 'freeLegalAdvice',
  home: 'home',
  'page-not-found': 'pageNotFound',
  'defendant-name-capture': 'defendantNameCapture',
  'defendant-name-confirmation': 'defendantNameConfirmation',
  'date-of-birth': 'dateOfBirth',
  'contact-preferences-telephone': 'contactPreferencesTelephone',
  'contact-preferences-text-message': 'contactPreferencesTextMessage',
  'dispute-claim-interstitial': 'disputeClaimInterstitial',
  'confirmation-of-notice-date-when-not-provided': 'noticeDateWhenNotProvided',
  'confirmation-of-notice-given': 'confirmationOfNoticeGiven',
  'non-rent-arrears-dispute': 'nonRentArrearsDispute',
  'confirmation-of-notice-date-when-provided': 'noticeDateWhenProvided',
  'rent-arrears-dispute': 'rentArrears',
  'payment-interstitial': 'paymentInterstitial',
  'repayments-made': 'repaymentsMade',
  'landlord-registered': 'landlordRegistered',
  'tenancy-date-unknown': 'tenancyDateUnknown',
  'tenancy-date-details': 'tenancyDateDetails',
  'tenancy-type-details': 'tenancyTypeDetails',
  'repayments-agreed': 'repaymentsAgreed',
  'landlord-licensed': 'landlordLicensed',
  'written-terms': 'writtenTerms',
  'contact-preferences-email-or-post': 'contactPreferenceEmailOrPost',
  'your-circumstances': 'yourCircumstances',
  'exceptional-hardship': 'exceptionalHardship',
  'do-any-other-adults-live-in-your-home': 'doAnyOtherAdultsLiveInYourHome',
  'would-you-have-somewhere-else-to-live-if-you-had-to-leave-your-home':
    'wouldYouHaveSomewhereElseToLiveIfYouHadToLeaveYourHome',
  'installment-payments': 'installmentPayments',
  'how-much-afford-to-pay': 'howMuchAffordToPay',
  'your-household-and-circumstances': 'yourHouseholdAndCircumstances',
  'do-you-have-any-dependant-children': 'doYouHaveAnyDependantChildren',
  'do-you-have-any-other-dependants': 'doYouHaveAnyOtherDependants',
  'choose-an-application': 'chooseAnApplication',
  'check-your-answers': 'checkYourAnswers',
  'ask-to-adjourn-the-court-hearing': 'askToAdjournTheCourtHearing',
  'ask-the-court-to-set-aside-the-order': 'askTheCourtToSetAsideTheOrder',
  'ask-the-court-to-make-an-order': 'askTheCourtToMakeAnOrder',
  'is-the-court-hearing-in-the-next-14-days': 'isTheCourtHearingInTheNext14Days',
  'do-you-need-help-paying-the-fee': 'doYouNeedHelpPayingTheFee',
  'have-you-already-applied-for-help': 'haveYouAlreadyAppliedForHelp',
  'have-the-other-parties-agreed-to-this-application': 'haveTheOtherPartiesAgreedToThisApplication',
  'you-need-to-apply-for-help-with-your-application-fee': 'youNeedToApplyForHelpWithYouApplicationFee',
  'what-order-do-you-want-the-court-to-make-and-why': 'whatOrderDoYouWantTheCourtToMakeAndWhy',
  'are-there-any-reasons-that-this-application-should-not-be-shared':
    'areThereAnyReasonsThatThisApplicationShouldNotBeShared',
  'do-you-want-to-upload-documents-to-support-your-application': 'doYouWantToUploadDocumentsToSupportYourApplication',
  'upload-documents-to-support-your-application': 'uploadDocumentsToSupportYourApplication',
  'which-language-did-you-use-to-complete-this-service': 'whichLanguageDidYouUseToCompleteThisService',
  'application-submitted': 'applicationSubmitted',
};
