export default {
  'start-now': 'startNow',
  'free-legal-advice': 'freeLegalAdvice',
  home: 'home',
  'page-not-found': 'pageNotFound',
  'defendant-name-capture': 'defendantNameCapture',
  'defendant-name-confirmation': 'defendantNameConfirmation',
  'contact-preferences-telephone': 'contactPreferencesTelephone',
  'contact-preferences-text-message': 'contactPreferencesTextMessage',
  'dispute-claim-interstitial': 'disputeClaimInterstitial',
  'date-of-birth': 'dateOfBirth',
  'confirmation-of-notice-date-when-not-provided': 'noticeDateWhenNotProvided',
  'confirmation-of-notice-given': 'confirmationOfNoticeGiven',
  'non-rent-arrears-dispute': 'nonRentArrearsDispute',
  'confirmation-of-notice-date-when-provided': 'noticeDateWhenProvided',
  'rent-arrears-dispute': 'rentArrears',
  'payment-interstitial': 'paymentInterstitial',
  'repayments-made': 'repaymentsMade',
  'landlord-registered': 'landlordRegistered',
  'tenancy-date-unknown': 'tenancyDateUnknown',
  'tenancy-date-details': 'tenancyDateDetails',
  'tenancy-type-details': 'tenancyTypeDetails',
  'repayments-agreed': 'repaymentsAgreed',
  'landlord-licensed': 'landlordLicensed',
  'written-terms': 'writtenTerms',
  'contact-preferences-email-or-post': 'contactPreferenceEmailOrPost',
  'do-any-other-adults-live-in-your-home': 'doAnyOtherAdultsLiveInYourHome',
  'would-you-have-somewhere-else-to-live-if-you-had-to-leave-your-home':
    'wouldYouHaveSomewhereElseToLiveIfYouHadToLeaveYourHome',
  'your-household-and-circumstances': 'yourHouseholdAndCircumstances',
  'do-you-have-any-dependant-children': 'doYouHaveAnyDependantChildren',
  'do-you-have-any-other-dependants': 'doYouHaveAnyOtherDependants',
  'do-any-other-adults-live-in-your-home': 'doAnyOtherAdultsLiveInYourHome',
};
