export default {
  'start-now': 'startNow',
  'free-legal-advice': 'freeLegalAdvice',
  home: 'home',
  'page-not-found': 'pageNotFound',
  'defendant-name-capture': 'defendantNameCapture',
  'contact-preferences-telephone': 'contactByTelephone',
  'dispute-claim-interstitial': 'disputeClaimInterstitial',
  'date-of-birth': 'dateOfBirth',
  'confirmation-of-notice-date-when-not-provided': 'noticeDateUnknown',
  'confirmation-of-notice-given': 'noticeDetails',
  'non-rent-arrears-dispute': 'nonRentArrearsDispute',
  'confirmation-of-notice-date-when-provided': 'noticeDateKnown',
  'rent-arrears-dispute': 'rentArrearsDispute',
  'payment-interstitial': 'payment-interstitial',
  'repayments-made': 'repaymentsMade',
  'contact-preferences-text-message': 'contactByTextMessage',
};
