import { flowConfig as citizenFlowConfig } from './flow.config';

import type { JourneyFlowConfig } from '@modules/steps/stepFlow.interface';

const legalrepStepOrder: JourneyFlowConfig['stepOrder'] = [
  'start-now',
  'defendant-name-confirmation',
  'defendant-name-capture',
  'defendant-date-of-birth',
  'correspondence-address',
  'contact-preferences-email-or-post',
  'contact-preferences-telephone',
  'contact-preferences-text-message',
  'dispute-claim-interstitial',
  'landlord-registered',
  'landlord-licensed',
  'written-terms',
  'tenancy-type-details',
  'tenancy-date-details',
  'tenancy-date-unknown',
  'confirmation-of-notice-given',
  'confirmation-of-notice-date-when-provided',
  'confirmation-of-notice-date-when-not-provided',
  'rent-arrears-dispute',
  'non-rent-arrears-dispute',
  'counter-claim',
  'payment-interstitial',
  'repayments-made',
  'repayments-agreed',
  'installment-payments',
  'how-much-afford-to-pay',
  'your-household-and-circumstances',
  'do-you-have-any-dependant-children',
  'do-you-have-any-other-dependants',
  'do-any-other-adults-live-in-your-home',
  'would-you-have-somewhere-else-to-live-if-you-had-to-leave-your-home',
  'your-circumstances',
  'exceptional-hardship',
  'income-and-expenditure',
  'what-regular-income-do-you-receive',
  'have-you-applied-for-universal-credit',
  'priority-debts',
  'priority-debt-details',
  'what-other-regular-expenses-do-you-have',
  'equality-and-diversity-start',
  'equality-and-diversity-end',
  'language-used',
  'check-your-answers',
  'end-now',
];

export const legalrepFlowConfig: JourneyFlowConfig = {
  ...citizenFlowConfig,
  journeyName: 'respondToClaimLegalrep',
  stepOrder: legalrepStepOrder,
};
