redis:
  enabled: false
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    enabled: false

nodejs:
  applicationPort: 3209
  aadIdentityName: pcs
  ingressHost: pcs-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/pcs/frontend:latest'
  keyVaults:
    pcs:
      secrets:
#        - name: app-insights-connection-string TODO: Re enable when app insights is working.
        - name: redis-connection-string
  environment:
    REDIS_TTL: 6000
    REDIS_HOST: 'pcs-{{ .Values.global.environment }}.redis.cache.windows.net'
