redis:
  enabled: false
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    enabled: false

nodejs:
  applicationPort: 3209
  aadIdentityName: pcs
  ingressHost: pcs-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/pcs/frontend:latest',
    keyVaults:
      pcs:
        secrets:
          - AppInsightsInstrumentationKey
          - name: api-POSTGRES-PASS
            alias: PCS_DB_PASSWORD
  environment:
    REDIS_TTL: 6000
    PCS_DB_USER_NAME: pgadmin
    PCS_DB_NAME: pcs
    DRAFT_STORE_DB_CONN_OPTIONS: ?sslmode=require&gssEncMode=disable
    PCS_DB_HOST: pcs-{{ .Values.global.environment }}.postgres.database.azure.com
