import {
  CitizenCreateGenAppAPIAction,
  CreateCaseAPIAction,
  DocumentsAction,
  FetchPINsAndValidateAccessCodeAPIAction,
  GenAppsAction,
  LoginAction,
  NavigateToUrlAction,
  RecordAnswers,
  RespondToClaimAction,
  TriggerPageFunctionalTestsAction,
  respondPossessionClaimAPIAction,
} from '../actions/custom-actions';
import { CitizenDashboardAction } from '../actions/custom-actions/citizenDashboard.action';
import { LinkSolicitorAPIAction } from '../actions/custom-actions/linkSolicitorAPI.action';
import { RespondToClaimLRAction } from '../actions/custom-actions/respondToClaimLR.action';
import {
  CheckAction,
  ClickButtonAction,
  ClickRadioButtonAction,
  ClickSummaryAction,
  ClickTabAction,
  InputTextAction,
  SelectAction,
  UploadFileAction,
} from '../actions/element-actions';
import { ClickLinkAction } from '../actions/element-actions/clickLink.action';
import { IAction } from '../interfaces';

export class ActionRegistry {
  private static actions: Map<string, IAction> = new Map<string, IAction>([
    ['check', new CheckAction()],
    ['uncheck', new CheckAction()],
    ['clickButton', new ClickButtonAction()],
    ['clickSummary', new ClickSummaryAction()],
    ['clickLink', new ClickLinkAction()],
    ['clickLinkAndVerifyNewTabTitle', new ClickLinkAction()],
    ['clickLinkAndVerifySameTabTitle', new ClickLinkAction()],
    ['clickRadioButton', new ClickRadioButtonAction()],
    ['clickTab', new ClickTabAction()],
    ['inputText', new InputTextAction()],
    ['select', new SelectAction()],
    ['uploadFile', new UploadFileAction()],
    ['login', new LoginAction()],
    ['createUser', new LoginAction()],
    ['navigateToUrl', new NavigateToUrlAction()],
    ['createCaseAPI', new CreateCaseAPIAction()],
    ['submitCaseAPI', new CreateCaseAPIAction()],
    ['citizenCreateGenAppAPI', new CitizenCreateGenAppAPIAction()],
    ['respondPossessionClaimAPI', new respondPossessionClaimAPIAction()],
    ['citizenDashboard', new CitizenDashboardAction()],
    ['validateViewAllApplications', new CitizenDashboardAction()],
    ['verifyRespondToClaimNotificationAndTag', new CitizenDashboardAction()],
    ['verifyNavigationFromNotificationLink', new CitizenDashboardAction()],
    ['deleteCaseRole', new CreateCaseAPIAction()],
    ['fetchPINsAPI', new FetchPINsAndValidateAccessCodeAPIAction()],
    ['validateAccessCodeAPI', new FetchPINsAndValidateAccessCodeAPIAction()],
    ['startEvidenceUpload', new DocumentsAction()],
    ['validateViewDocuments', new DocumentsAction()],
    ['verifyDocumentRelatesToApplication', new DocumentsAction()],
    ['selectLegalAdvice', new RespondToClaimAction()],
    ['inputDefendantDetails', new RespondToClaimAction()],
    ['enterDateOfBirthDetails', new RespondToClaimAction()],
    ['inputErrorValidation', new RespondToClaimAction()],
    ['confirmDefendantDetails', new RespondToClaimAction()],
    ['selectCorrespondenceAddressKnown', new RespondToClaimAction()],
    ['selectCorrespondenceAddressUnKnown', new RespondToClaimAction()],
    ['selectContactByTelephone', new RespondToClaimAction()],
    ['selectContactByTextMessage', new RespondToClaimAction()],
    ['selectNoticeDetails', new RespondToClaimAction()],
    ['enterNoticeDateKnown', new RespondToClaimAction()],
    ['enterNoticeDateUnknown', new RespondToClaimAction()],
    ['disputeClaimInterstitial', new RespondToClaimAction()],
    ['readPaymentInterstitial', new RespondToClaimAction()],
    ['repaymentsMade', new RespondToClaimAction()],
    ['selectLandlordRegistered', new RespondToClaimAction()],
    ['selectWrittenTerms', new RespondToClaimAction()],
    ['enterTenancyStartDetailsUnKnown', new RespondToClaimAction()],
    ['triggerFunctionalTests', new TriggerPageFunctionalTestsAction()],
    ['repaymentsAgreed', new RespondToClaimAction()],
    ['selectTenancyStartDateKnown', new RespondToClaimAction()],
    ['disputingOtherPartsOfTheClaim', new RespondToClaimAction()],
    ['tenancyOrContractTypeDetails', new RespondToClaimAction()],
    ['selectLandlordLicensed', new RespondToClaimAction()],
    ['selectContactPreferenceEmailOrPost', new RespondToClaimAction()],
    ['selectIfAnyOtherAdultsLiveInYourHouse', new RespondToClaimAction()],
    ['selectAlternativeAccommodation', new RespondToClaimAction()],
    ['readYourHouseholdAndCircumstances', new RespondToClaimAction()],
    ['doYouHaveAnyDependantChildren', new RespondToClaimAction()],
    ['doYouHaveAnyOtherDependants', new RespondToClaimAction()],
    ['installmentPayments', new RespondToClaimAction()],
    ['selectHowMuchAffordToPay', new RespondToClaimAction()],
    ['rentArrears', new RespondToClaimAction()],
    ['selectCounterClaimFee', new RespondToClaimAction()],
    ['selectIncomeAndExpenses', new RespondToClaimAction()],
    ['selectWhatRegularIncomeDoYouReceive', new RespondToClaimAction()],
    ['yourCircumstances', new RespondToClaimAction()],
    ['exceptionalHardship', new RespondToClaimAction()],
    ['selectUniversalCredit', new RespondToClaimAction()],
    ['selectPriorityDebts', new RespondToClaimAction()],
    ['enterPriorityDebtDetails', new RespondToClaimAction()],
    ['selectCounterClaim', new RespondToClaimAction()],
    ['selectWhatOtherRegularExpensesDoYouHave', new RespondToClaimAction()],
    ['readReasonableAdjustmentsTriage', new RespondToClaimAction()],
    ['counterClaimHaveYouAppliedForHelpWithFee', new RespondToClaimAction()],
    ['otherConsiderations', new RespondToClaimAction()],
    ['uploadFiles', new RespondToClaimAction()],
    ['languageUsed', new RespondToClaimAction()],
    ['selectWhatAreYouClaimingFor', new RespondToClaimAction()],
    ['counterClaimSpecificSumOfMoney', new RespondToClaimAction()],
    ['taskList', new RespondToClaimAction()],
    ['taskListStatus', new RespondToClaimAction()],
    ['resetRTCAnswerStore', new RespondToClaimAction()],
    ['retrieveCYATableDataRTC', new RespondToClaimAction()],
    ['validateCYARTC', new RespondToClaimAction()],
    ['validateRTCSectionCYA', new RespondToClaimAction()],
    ['getCaseAPI', new CreateCaseAPIAction()],
    ['linkSolicitorAPI', new LinkSolicitorAPIAction()],
    ['doYouWantToUploadFiles', new RespondToClaimAction()],
    ['uploadFilesToSupportCounterclaim', new RespondToClaimAction()],

    //ADD GEN APPS details below this line
    ['chooseAnApplication', new GenAppsAction()],
    ['confirmIfCourtHearingInNext14Days', new GenAppsAction()],
    ['doYouNeedHelpPayingFee', new GenAppsAction()],
    ['confirmYouHaveAppliedForFeeHelp', new GenAppsAction()],
    ['confirmOtherPartiesAgreed', new GenAppsAction()],
    ['reasonsApplicationShouldNotBeShared', new GenAppsAction()],
    ['inputErrorValidationGenApp', new GenAppsAction()],
    ['selectLanguageUsedToComplete', new GenAppsAction()],
    ['retrieveCYATableData', new GenAppsAction()],
    ['validateCYA', new GenAppsAction()],
    ['confirmDocumentToUpload', new GenAppsAction()],
    ['recordUserEntry', new RecordAnswers()],
    ['confirmOrderDoYouWant', new GenAppsAction()],
    ['confirmOrderDoYouWant', new GenAppsAction()],
    ['reviewCYA', new GenAppsAction()],
    ['selectStatementOfTruth', new GenAppsAction()],
    ['reviewAndUpdateCYA', new GenAppsAction()],
    ['otherConsiderations', new RespondToClaimAction()],
    ['accessYourCase', new RespondToClaimAction()],
    ['selectClaimAgainstWhom', new RespondToClaimAction()],
    ['counterClaimAbout', new RespondToClaimAction()],
    ['counterClaimOrderOtherThanSum', new RespondToClaimAction()],
    ['uploadFilesGenApps', new GenAppsAction()],

    //LR details below
    ['selectNoticeDetailsLR', new RespondToClaimLRAction()],
    ['enterTenancyStartDetailsUnKnownLR', new RespondToClaimLRAction()],
    ['disputingOtherPartsOfTheClaimLR', new RespondToClaimLRAction()],
    ['enterNoticeDateUnknownLR', new RespondToClaimLRAction()],
    ['doesTheDependantHaveChildrenLR', new RespondToClaimLRAction()],
    ['otherDependantsLR', new RespondToClaimLRAction()],
    ['otherAdultsLR', new RespondToClaimLRAction()],
    ['alternativeAccommodationLR', new RespondToClaimLRAction()],
    ['circumstancesLR', new RespondToClaimLRAction()],
    ['exceptionalHardshipLR', new RespondToClaimLRAction()],
    ['selectIncomeAndExpensesLR', new RespondToClaimLRAction()],
    ['representationLR', new RespondToClaimLRAction()],
    ['selectWhatRegularIncomeDoTheyReceiveLR', new RespondToClaimLRAction()],
    ['selectPriorityDebtsLR', new RespondToClaimLRAction()],
    ['enterPriorityDebtDetailsLR', new RespondToClaimLRAction()],
    ['selectExpensesLR', new RespondToClaimLRAction()],
    ['otherConsiderationsLR', new RespondToClaimLRAction()],
  ]);

  static getAction(actionName: string): IAction {
    const action = this.actions.get(actionName);
    if (!action) {
      throw new Error(
        `Action '${actionName}' is not registered. Available actions: ${Array.from(this.actions.keys()).join(', ')}`
      );
    }
    return action;
  }

  static getAvailableActions(): string[] {
    return Array.from(this.actions.keys());
  }
}
