import {
  CitizenCreateGenAppAPIAction,
  CreateCaseAPIAction,
  DocumentsAction,
  FetchPINsAndValidateAccessCodeAPIAction,
  GenAppsAction,
  LaunchDarklyAction,
  LoginAction,
  NavigateToUrlAction,
  RecordAnswers,
  RespondToClaimAction,
  TriggerPageFunctionalTestsAction,
  respondPossessionClaimAPIAction,
} from '../actions/custom-actions';
import { CitizenDashboardAction } from '../actions/custom-actions/citizenDashboard.action';
import { LinkSolicitorAPIAction } from '../actions/custom-actions/linkSolicitorAPI.action';
import { PaymentAction } from '../actions/custom-actions/payment.action';
import { RespondPossessionClaimLRMidEventAPIAction } from '../actions/custom-actions/respondPossessionClaimSolicitorMidEventAPI.action';
import { RespondToClaimLRAction } from '../actions/custom-actions/respondToClaimLR.action';
import { SubmitPossessionClaimResponseAPIAction } from '../actions/custom-actions/respondToClaimSubmitAPIForLR.action';
import { CheckAction, ClickButtonAction, ClickRadioButtonAction, ClickSummaryAction, ClickTabAction, InputTextAction, SelectAction, UploadFileAction } from '../actions/element-actions';
import { ClickLinkAction } from '../actions/element-actions/clickLink.action';
import { IAction } from '../interfaces';

export class ActionRegistry {
  private static actions: Map<string, IAction> = new Map<string, IAction>([
    ['check', new CheckAction()],
    ['uncheck', new CheckAction()],
    ['When the user clicks the button', new ClickButtonAction()],
    ['clickSummary', new ClickSummaryAction()],
    ['clickLink', new ClickLinkAction()],
    ['clickLinkAndSwitchToNewTab', new ClickLinkAction()],
    ['clickLinkAndVerifyNewTabTitle', new ClickLinkAction()],
    ['clickLinkAndVerifySameTabTitle', new ClickLinkAction()],
    ['clickRadioButton', new ClickRadioButtonAction()],
    ['clickTab', new ClickTabAction()],
    ['inputText', new InputTextAction()],
    ['select', new SelectAction()],
    ['uploadFile', new UploadFileAction()],
    ['login', new LoginAction()],
    ['createUser', new LoginAction()],
    ['navigateToUrl', new NavigateToUrlAction()],
    ['createCaseAPI', new CreateCaseAPIAction()],
    ['submitCaseAPI', new CreateCaseAPIAction()],
    ['citizenCreateGenAppAPI', new CitizenCreateGenAppAPIAction()],
    ['respondPossessionClaimAPI', new respondPossessionClaimAPIAction()],
    ['deleteCaseRole', new CreateCaseAPIAction()],
    ['updatePaymentAPI', new CreateCaseAPIAction()],
    ['linkDefendantToSolicitorForCaseAPI', new LinkSolicitorAPIAction()],
    ['fetchPINsAPI', new FetchPINsAndValidateAccessCodeAPIAction()],
    ['validateAccessCodeAPI', new FetchPINsAndValidateAccessCodeAPIAction()],
    ['skipTestIfLdFlagDisabled', new LaunchDarklyAction()],
    ['selectPaymentOptions', new PaymentAction()],

    //Citizen Dashboard
    ['citizenDashboard', new CitizenDashboardAction()],
    ['validateViewAllApplications', new CitizenDashboardAction()],
    ['verifyRespondToClaimNotificationAndTag', new CitizenDashboardAction()],
    ['verifyNavigationFromNotificationLink', new CitizenDashboardAction()],
    ['verifyResponseDetailsOnViewTheResponsePage', new CitizenDashboardAction()],
    ['verifyClaimDetailsOnViewTheClaimPage', new CitizenDashboardAction()],

    //Respond to claim
    ['When the user selects the legal advice option', new RespondToClaimAction()],
    ['When the user enters the defendant details', new RespondToClaimAction()],
    ['And the user enters the date of birth details', new RespondToClaimAction()],
    ['inputErrorValidation', new RespondToClaimAction()],
    ['confirmDefendantDetails', new RespondToClaimAction()],
    ['And the user selects whether the correspondence address is known', new RespondToClaimAction()],
    ['selectCorrespondenceAddressUnKnown', new RespondToClaimAction()],
    ['And the user selects contact by telephone', new RespondToClaimAction()],
    ['selectContactByTextMessage', new RespondToClaimAction()],
    ['selectNoticeDetails', new RespondToClaimAction()],
    ['enterNoticeDateKnown', new RespondToClaimAction()],
    ['enterNoticeDateUnknown', new RespondToClaimAction()],
    ['And the user selects whether they have a solicitor', new RespondToClaimAction()],
    ['askYourSolicitorToRespond', new RespondToClaimAction()],
    ['When the user responds to the dispute claim interstitial', new RespondToClaimAction()],
    ['readPaymentInterstitial', new RespondToClaimAction()],
    ['repaymentsMade', new RespondToClaimAction()],
    ['selectLandlordRegistered', new RespondToClaimAction()],
    ['exemptLandLord', new RespondToClaimAction()],
    ['selectWrittenTerms', new RespondToClaimAction()],
    ['And the user enters the tenancy start details when unknown', new RespondToClaimAction()],
    ['triggerFunctionalTests', new TriggerPageFunctionalTestsAction()],
    ['repaymentsAgreed', new RespondToClaimAction()],
    ['selectTenancyStartDateKnown', new RespondToClaimAction()],
    ['disputingOtherPartsOfTheClaim', new RespondToClaimAction()],
    ['And the user enters the tenancy or contract type details', new RespondToClaimAction()],
    ['selectLandlordLicensed', new RespondToClaimAction()],
    ['And the user selects the contact preference (email or post)', new RespondToClaimAction()],
    ['selectIfAnyOtherAdultsLiveInYourHouse', new RespondToClaimAction()],
    ['And the user navigates to the task list subsection', new RespondToClaimAction()],
    ['selectAlternativeAccommodation', new RespondToClaimAction()],
    ['readYourHouseholdAndCircumstances', new RespondToClaimAction()],
    ['doYouHaveAnyDependantChildren', new RespondToClaimAction()],
    ['doYouHaveAnyOtherDependants', new RespondToClaimAction()],
    ['installmentPayments', new RespondToClaimAction()],
    ['selectHowMuchAffordToPay', new RespondToClaimAction()],
    ['rentArrears', new RespondToClaimAction()],
    ['selectCounterClaimFee', new RespondToClaimAction()],
    ['selectIncomeAndExpenses', new RespondToClaimAction()],
    ['selectWhatRegularIncomeDoYouReceive', new RespondToClaimAction()],
    ['yourCircumstances', new RespondToClaimAction()],
    ['exceptionalHardship', new RespondToClaimAction()],
    ['selectUniversalCredit', new RespondToClaimAction()],
    ['selectPriorityDebts', new RespondToClaimAction()],
    ['enterPriorityDebtDetails', new RespondToClaimAction()],
    ['selectCounterClaim', new RespondToClaimAction()],
    ['selectWhatOtherRegularExpensesDoYouHave', new RespondToClaimAction()],
    ['readReasonableAdjustmentsTriage', new RespondToClaimAction()],
    ['counterClaimHaveYouAppliedForHelpWithFee', new RespondToClaimAction()],
    ['otherConsiderations', new RespondToClaimAction()],
    ['uploadFiles', new RespondToClaimAction()],
    ['languageUsed', new RespondToClaimAction()],
    ['inputCounterClaimPaymentDetails', new RespondToClaimAction()],
    ['validateCounterClaimApplicationFee', new RespondToClaimAction()],
    ['selectWhatAreYouClaimingFor', new RespondToClaimAction()],
    ['counterClaimSpecificSumOfMoney', new RespondToClaimAction()],
    ['And the user navigates to the task list subsection', new RespondToClaimAction()],
    ['taskListStatus', new RespondToClaimAction()],
    ['resetRTCAnswerStore', new RespondToClaimAction()],
    ['And the user retrieves the check‑your‑answers table data for the RTC section', new RespondToClaimAction()],
    ['validateCYARTC', new RespondToClaimAction()],
    ['changeAnswerOnFinalCYA', new RespondToClaimAction()],
    ['selectStatementOfTruthRTC', new RespondToClaimAction()],
    ['Then the user validates the RTC section on the check‑your‑answers page', new RespondToClaimAction()],
    ['getCaseAPI', new CreateCaseAPIAction()],
    ['linkSolicitorAPI', new LinkSolicitorAPIAction()],
    ['doYouWantToUploadFiles', new RespondToClaimAction()],
    ['uploadFilesToSupportCounterclaim', new RespondToClaimAction()],

    //Documents
    ['startEvidenceUpload', new DocumentsAction()],
    ['uploadDocuments', new DocumentsAction()],
    ['verifyCheckYourAnswers', new DocumentsAction()],
    ['validateViewDocuments', new DocumentsAction()],
    ['verifyDocumentRelatesToApplication', new DocumentsAction()],

    //ADD GEN APPS details below this line
    ['chooseAnApplication', new GenAppsAction()],
    ['confirmIfCourtHearingInNext14Days', new GenAppsAction()],
    ['doYouNeedHelpPayingFee', new GenAppsAction()],
    ['confirmYouHaveAppliedForFeeHelp', new GenAppsAction()],
    ['confirmOtherPartiesAgreed', new GenAppsAction()],
    ['reasonsApplicationShouldNotBeShared', new GenAppsAction()],
    ['inputErrorValidationGenApp', new GenAppsAction()],
    ['selectLanguageUsedToComplete', new GenAppsAction()],
    ['retrieveCYATableData', new GenAppsAction()],
    ['validateCYA', new GenAppsAction()],
    ['confirmDocumentToUpload', new GenAppsAction()],
    ['recordUserEntry', new RecordAnswers()],
    ['confirmOrderDoYouWant', new GenAppsAction()],
    ['confirmOrderDoYouWant', new GenAppsAction()],
    ['reviewCYA', new GenAppsAction()],
    ['selectStatementOfTruth', new GenAppsAction()],
    ['reviewAndUpdateCYA', new GenAppsAction()],
    ['otherConsiderations', new RespondToClaimAction()],
    ['accessYourCase', new RespondToClaimAction()],
    ['selectClaimAgainstWhom', new RespondToClaimAction()],
    ['counterClaimAbout', new RespondToClaimAction()],
    ['counterClaimOrderOtherThanSum', new RespondToClaimAction()],
    ['selectReasonableAdjustments', new RespondToClaimAction()],
    ['selectEqualityAndDiversity', new RespondToClaimAction()],
    ['uploadFilesGenApps', new GenAppsAction()],
    ['payForApplication', new GenAppsAction()],
    ['inputPaymentDetails', new GenAppsAction()],
    ['confirmPayment', new GenAppsAction()],
    ['verifyApplicationSubmitted', new GenAppsAction()],

    //LR details below
    ['selectNoticeDetailsLR', new RespondToClaimLRAction()],
    ['enterTenancyStartDetailsUnKnownLR', new RespondToClaimLRAction()],
    ['disputingOtherPartsOfTheClaimLR', new RespondToClaimLRAction()],
    ['enterNoticeDateUnknownLR', new RespondToClaimLRAction()],
    ['doesTheDependantHaveChildrenLR', new RespondToClaimLRAction()],
    ['otherDependantsLR', new RespondToClaimLRAction()],
    ['otherAdultsLR', new RespondToClaimLRAction()],
    ['alternativeAccommodationLR', new RespondToClaimLRAction()],
    ['circumstancesLR', new RespondToClaimLRAction()],
    ['selectExceptionalHardshipLR', new RespondToClaimLRAction()],
    ['selectIncomeAndExpensesLR', new RespondToClaimLRAction()],
    ['representationLR', new RespondToClaimLRAction()],
    ['selectResumeResponseLR', new RespondToClaimLRAction()],
    ['createDraftResponseLR', new RespondToClaimLRAction()],
    ['reopenStartNowLR', new RespondToClaimLRAction()],
    ['selectWhatRegularIncomeDoTheyReceiveLR', new RespondToClaimLRAction()],
    ['selectPriorityDebtsLR', new RespondToClaimLRAction()],
    ['enterPriorityDebtDetailsLR', new RespondToClaimLRAction()],
    ['selectExpensesLR', new RespondToClaimLRAction()],
    ['otherConsiderationsLR', new RespondToClaimLRAction()],
    ['rentArrearsLR', new RespondToClaimLRAction()],
    ['previousPaymentsLR', new RespondToClaimLRAction()],
    ['repaymentAgreedLR', new RespondToClaimLRAction()],
    ['selectUniversalCreditLR', new RespondToClaimLRAction()],
    ['selectCorrespondenceAddressUnknownLR', new RespondToClaimLRAction()],
    ['enterNoticeDateKnownLR', new RespondToClaimLRAction()],
    ['selectCounterClaimLR', new RespondToClaimLRAction()],
    ['selectWhatAreYouClaimingForLR', new RespondToClaimLRAction()],
    ['counterClaimSpecificSumOfMoneyLR', new RespondToClaimLRAction()],
    ['selectCounterClaimFeeLR', new RespondToClaimLRAction()],
    ['selectClaimAgainstWhomLR', new RespondToClaimLRAction()],
    ['counterClaimAboutLR', new RespondToClaimLRAction()],
    ['installmentPaymentsLR', new RespondToClaimLRAction()],
    ['selectHowMuchAffordToPayLR', new RespondToClaimLRAction()],
    ['counterClaimOrderOtherThanSumLR', new RespondToClaimLRAction()],
    ['counterClaimHaveYouAppliedForHelpWithFeeLR', new RespondToClaimLRAction()],
    ['uploadAdditionalDocumentsLR', new RespondToClaimLRAction()],
    ['doYouWantToUploadFilesLR', new RespondToClaimLRAction()],
    ['uploadFilesToSupportCounterclaimLR', new RespondToClaimLRAction()],
    ['submitPossessionClaimResponseLRAPI', new SubmitPossessionClaimResponseAPIAction()],
    ['midEventRespondPossessionClaimLRAPI', new RespondPossessionClaimLRMidEventAPIAction()],
    ['confirmDefendantDetailsLR', new RespondToClaimLRAction()],
    ['enterDateOfBirthDetailsLR', new RespondToClaimLRAction()],
    ['selectCorrespondenceAddressLR', new RespondToClaimLRAction()],
    ['languageUsedLR', new RespondToClaimLRAction()],
    ['selectStatementOfTruthRTCLR', new RespondToClaimLRAction()],
    ['emailConfirmationLR', new RespondToClaimLRAction()],
    ['exemptLandlordLR', new RespondToClaimLRAction()],
    ['selectTenancyStartDateKnownLR', new RespondToClaimLRAction()],
    ['tenancyOrContractTypeDetailsLR', new RespondToClaimLRAction()],
    ['selectWrittenTermsLR', new RespondToClaimLRAction()],
  ]);

  static getAction(actionName: string): IAction {
    const action = this.actions.get(actionName);
    if (!action) {
      throw new Error(`Action '${actionName}' is not registered. Available actions: ${Array.from(this.actions.keys()).join(', ')}`);
    }
    return action;
  }

  static getAvailableActions(): string[] {
    return Array.from(this.actions.keys());
  }
}
